require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
use_modular_headers!

target 'CashGrab' do
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'
  # React Native Maps dependencie
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  
  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'
  
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  
  
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false


  target 'CashGrabTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!()
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'CashGrab-tvOS' do
  # Pods for CashGrab-tvOS

  target 'CashGrab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
