const Constants = {
  /* * Font Families * */
  fontLight: 'JostLight',
  fontRegular: 'JostRegular',
  fontBold: 'JostBold',
  /* * Screens * */
  splash: 'Splash',
  login: 'Login',
  createAccount: 'CreateAccount',
  signUp: 'SignUp',
  forgetPassword: 'ForgetPassword',
  otp: 'OTP',
  allCategories: 'AllCategories',
  vendorAllCategories: 'VendorAllCategories',
  advanceBooking: 'AdvanceBooking',
  bookingConfirmed: 'BookingConfirmed',
  filter: 'Filter',
  editProfile: 'EditProfile',
  vendorEditProfile: 'VendorEditProfile',
  viewVendorProfile: 'ViewVendorProfile',
  chat: 'Chat',
  chatListing: 'ChatListing',
  vendorSingleCategory: 'VendorSingleCategory',
  viewJob: 'ViewJob',
  faq: 'Faq',
  dateTimeSlots: 'DateTimeSlots',
  /* * tabs * */
  tabNavigator: 'TabNavigator',
  home: 'Home',
  vendorHome: 'VendorHome',
  nearby: 'Nearby',
  notifications: 'Notifications',
  plus: 'Plus',
  profile: 'Profile',
  vendorProfile: 'VendorProfile',
  more: 'More',
  settings: 'Settings',
  /* * drawer * */
  drawerNavigator: 'DrawerNavigator',
  support: 'Support',
  termsAndConditionsScreen: 'TermsAndConditions',
  logOut: 'Log Out',
};

export default Constants;
