const Images = {
  arrowBack: require('../assets/arrow_left.png'),
  arrowForward: require('../assets/arrow_right.png'),
  tickYellow: require('../assets/tick_yellow.png'),
  tickVerified: require('../assets/tick_verified.png'),
  iconFilter: require('../assets/icon_filter.png'),
  emp1: require('../assets/emp1.png'),
  emp2: require('../assets/emp2.png'),
  emp3: require('../assets/emp3.png'),
  emp4: require('../assets/emp4.png'),
  banner1: require('../assets/food-banner1.jpg'),
  banner2: require('../assets/food-banner2.jpg'),
  banner3: require('../assets/food-banner3.jpg'),
  banner4: require('../assets/food-banner4.jpg'),
  banner5: require('../assets/food-banner5.jpg'),
  mapMarker: require('../assets/map_marker.png'),
  handHoldingPhone: require('../assets/icon_hand_holding_phone.png'),
  employeeThumbsUp: require('../assets/icon_employee_thumbs_up.png'),
  employeeHoldingBox: require('../assets/icon_box.png'),
  userPlaceHolder: require('../assets/icon_user_placeholder.png'),
  iconPencil: require('../assets/icon_pencil.png'),
  bgSplash: require('../assets/bg_splash.png'),
  logoCashGrab: require('../assets/logo_cash_grab.png'),
  logoCashGrab2: require('../assets/logo_cash_grab2.png'),
  becomeAVendor: require('../assets/becomeavendor.png'),
  becomeAUser: require('../assets/becomeauser.png'),
  barBell: require('../assets/barbell.png'),
  barHome: require('../assets/barhome.png'),
  barHomeSelected: require('../assets/barhomeselected.png'),
  barPlus: require('../assets/barplus.png'),
  barMore: require('../assets/barmore.png'),
  barProfile: require('../assets/barprofile.png'),
};

export default Images;
